# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 8a90dfacd7070e59af9f5230046eb94fdacc5d00507850087cec7a8d6bc5c1397cd6b9b01cece159cb522170672a52637cbcb0a52d5053ff5ae598e72fc9a27f

test:
  secret_key_base: 32f63e79f2a0758d4667efaa17c3aa0562db161193effd81adf15b08f58474585360f82080cc23344e4ba1618921f7523e388c3458a2c32cea6558af3ce2ad60

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
